export const PERMISSION_MAP = {
  SUPER_ADMIN: [
    'dashboard.view',
    'dashboard.all_warehouses',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'inventory.price.view',
    'inventory.delete',
    'transaction.stock_in',
    'transaction.stock_out',
    'transaction.transfer',
    'transaction.history.view',
    'transaction.delete',
    'reports.stock',
    'reports.financial',
    'reports.expenditure',
    'reports.export',
    'users.manage',
    'settings.system',
    'settings.profile',
  ],
  WH_MANAGER: [
    'dashboard.view',
    'inventory.view',
    'inventory.create',
    'inventory.edit',
    'transaction.stock_in',
    'transaction.stock_out',
    'transaction.transfer',
    'transaction.approve_transfer',
    'transaction.history.view',
    'reports.stock',
    'reports.export',
    'settings.profile',
  ],
  STAFF: [
    'dashboard.view',
    'inventory.view',
    'transaction.stock_in',
    'transaction.stock_out',
    'transaction.history.own',
    'settings.profile',
  ],
} as const;

export type Permission = (typeof PERMISSION_MAP)[keyof typeof PERMISSION_MAP][number];
